appname: "ZipApp"
layout: "main"
charset: "UTF-8"
session: YAML
template: "xslate"
engines:
  xslate:
    syntax: TTerse
    suffix: '.tt'
    cache: 1
    cache_dir: xslate_cache
plugins:
  DBIC:
    zip:
      schema_class: ZipApp::Schema
      dsn: "dbi:SQLite:dbname=data/zip.sqlite"
      options:
        sqlite_unicode: 1
        RaiseError: 1
