appname: "ZipApp"
layout: "main"
charset: "UTF-8"
session: YAML
template: "xslate"
engines:
  xslate:
    syntax: TTerse
    cache: 1
    cache_dir: xslate_cache
plugins:
  DBIC:
    zip:
      schema_class: ZipApp::Schema
      dsn: "dbi:SQLite:dbname=data/zip.sqlite"
      options:
        sqlite_unicode: 1
        RaiseError: 1
  "Auth::Twitter::Lite":
    consumer_key: 
    consumer_secret: 
    callback_url: "http://localhost:3000/auth/twitter/callback"
    callback_success: "/success"
    callback_fail: "/fail"
